### ISSUE TITLE
PHP7 notice

### ISSUE THREAD

**Issue by Sungodragon** [EllisLab/No-Follow#2]
PHP 7.08
EE 3.3.0 with No-follow

Only variables should be assigned by reference
user/addons/no_follow/pi.no_follow.php, line 49
Severity: E_NOTICE

**Comment by kevincupp** [comment]
Hi there. There is nothing but a comment on line 49 of pi.no_follow.php. Are you sure your copy of No Follow is up-to-date? I also don't see where we'd be calling a function that modifies its argument by reference nor where we're assigning the output of a function to a variable by reference, which is what usually causes this error.

**Comment by Sungodragon** [comment]
Yes, I will ask my team to dig bit more.

**Comment by Sungodragon** [comment]
I think its fixed after updating.
Thank you.
